### ISSUE TITLE
Credentials structure

### ISSUE THREAD

**Issue by vladimirstroganov** [pmaier1971/AutomatedEconomicAnalysis#1]
Could you add a sample file showing structure of the credentials, please?

**Comment by pmaier1971** [comment]
My file looks like this, but note that only the first line (the FRED key) is really necessary:

### 1 FRED
----
FRED_API_KEY <- "xxx".  # You’ll need a free API key to use fredr. See ?fredr_set_key().

### 2 Twitter
----
Following code needs to be run once, then can be commented out

api_key <-"xxx"
api_secret = "xxx"
 
token <- create_token(
   app = "app name",
   consumer_key = api_key,
   consumer_secret = api_secret)


### 3 Authenticate GMAIL
--- 
gm_auth_configure(path = "oauth.token.json")
gm_auth(email = "MyEmailAccount")

email <- gm_to(email, "recipient email")
email <- gm_from(email, "sender email")
email <- gm_subject(email, "email body")
